name: test

on:
  push:
    branches-ignore:
      - renovate/**
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version-file: "go.mod"
          cache: true

      - run: go test -race -count=5 ./...
