name: test

on:
  push:
    branches-ignore:
      - renovate/**
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache: true

      - run: go test -race -count=5 ./...
